name: {{project_name.snakeCase()}}
description: {{project_description}}
version: 0.1.0
homepage: https://www.takkan.org/

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  takkan_script:
    path: ../{{project_name.snakeCase()}}_script

dev_dependencies:
  test: ^1.16.0