name: trademation
repository: https://gitlab.com/dsowerby/trademation

packages:
  - packages/**

command:
  version:
    linkToCommits: true
    workspaceChangelog: true
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    # We are setting the concurrency to 1 because a higher concurrency can crash
    # the analysis server on low performance machines (like GitHub Actions).
    run: |
      melos exec -c 1 -- \
        dart analyze . --fatal-infos
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.


  check-format:
    exec: dart format --set-exit-if-changed .
    description: Check the format of a specific package in this project.

  format:
    exec: dart format .
    description: Format a specific package in this project.

  test:
    run: melos run test:dart --no-select && melos run test:flutter --no-select
    description: Run all Dart & Flutter tests in this project.

  test:dart:
    run: melos exec -c 1 --fail-fast -- "dart test test"
    description: Run Dart tests for a specific package in this project.
    select-package:
      flutter: false
      dir-exists: test

  test:flutter:
    run: melos exec -c 1 --fail-fast -- "flutter test test"
    description: Run Flutter tests for a specific package in this project.
    select-package:
      flutter: true
      dir-exists: test

  dep-outdated:
    description: Checks which dependencies have newer versions available.
    run: melos exec -c 1 -- "flutter pub outdated"

  dep-upgrade:
    description: Automatically upgrades package dependencies to the latest versions.
    run: melos exec -c 1 -- "flutter pub upgrade --major-versions"

  fix:
    description: Run Dart/Flutter automated fixes
    run: melos exec -c 1 -- "dart fix --apply"

  codegen:
    description: Run code generation using build_runner
    run: melos exec -c 1 -- "flutter pub run build_runner build --delete-conflicting-outputs && dart format --fix ."
    packageFilters:
      dependsOn: "build_runner"

