name: {{project_name.snakeCase()}}_script
description: Takkan Script for {{project_name}}
version: 0.1.0
homepage: https://www.takkan.org/

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  takkan_script:
    path: ../takkan_script

dev_dependencies:
  test: ^1.16.0