import 'package:flutter/material.dart';
import 'package:precept_client/data/cache_entry.dart';
import 'package:precept_client/data/data_source.dart';
import 'package:precept_client/data/document_cache.dart';
import 'package:precept_client/library/part_library.dart';
import 'package:precept_client/page/document_list_page.dart';
import 'package:precept_client/page/document_page.dart';
import 'package:precept_client/page/static_page.dart';
import 'package:precept_client/panel/static_panel.dart';
import 'package:precept_script/common/exception.dart';
import 'package:precept_script/common/log.dart';
import 'package:precept_script/common/script/content.dart';
import 'package:precept_script/data/select/data.dart';
import 'package:precept_script/data/select/multi.dart';
import 'package:precept_script/data/select/single.dart';
import 'package:precept_script/inject/inject.dart';
import 'package:precept_script/page/page.dart';
import 'package:precept_script/page/static_page.dart';
import 'package:precept_script/panel/panel.dart';
import 'package:precept_script/part/part.dart';
import 'package:precept_script/schema/schema.dart';
import 'package:precept_script/script/script.dart';

abstract class PageBuilder {
  Route<dynamic>? buildPage({
    required String route,
    required Map<String, dynamic> pageArguments,
    required BuildContext context,
    required DataBinding parentBinding,
    required PartLibrary partLibrary,
    required PScript script,
    required DocumentCache cache,
  });

  Widget createChild(
      {required DataContext dataContext,
      required PContent p,
      required DataBinding parentBinding,
      required ThemeData theme});
}

class DefaultPageBuilder implements PageBuilder {
  const DefaultPageBuilder();

  Route<dynamic>? buildPage({
    required String route,
    required Map<String, dynamic> pageArguments,
    required BuildContext context,
    required DataBinding parentBinding,
    required PartLibrary partLibrary,
    required PScript script,
    required DocumentCache cache,
  }) {
    final s = route.split('/');
    final autogenRoute = (s[0] == 'document' || s[0] == 'documents');
    return (autogenRoute)
        ? _autoGeneratedRoute(route, s, context, pageArguments, script, cache)
        : _staticRoute(route, context, pageArguments, parentBinding, script);
  }

  Route<dynamic>? _staticRoute(
    String route,
    BuildContext context,
    Map<String, dynamic> pageArguments,
    DataBinding parentBinding,
    PScript script,
  ) {
    final pageConfig = script.routes[route];
    if (pageConfig == null) {
      return null;
    }
    final PPageStatic pageCfg = pageConfig as PPageStatic;
    final theme = Theme.of(context);
    final dataContext = StaticDataContext(
      parentDataContext: NullDataContext(),
    );
    final pageBuilder = inject<PageBuilder>();
    final pageWidget = StaticPage(
      pageBuilder: pageBuilder,
      config: pageCfg,
      dataContext: dataContext,
      route: route,
    );
    return constructRoute(
      route,
      pageArguments,
      pageWidget,
    );
  }

  List<Widget> createChildren(
      {required DataContext dataContext,
      required List<PContent> children,
      required DataBinding parentBinding,
      required ThemeData theme}) {
    final output = List<Widget>.empty(growable: true);

    /// Using switch stops from detecting PPart sub-classes
    for (PContent p in children) {
      if (p is PPanel) {
        final panel = panelBuilder(
          config: p,
          parentDataContext: dataContext,
          parentBinding: parentBinding,
          theme: theme,
        );
        output.add(panel);
      } else if (p is PPart) {
        final part = partLibrary.partBuilder(
          partConfig: p,
          dataContext: dataContext,
          pageArguments: const {},
          theme: theme,
          parentBinding: parentBinding,
        );
        output.add(part);
      }
    }
    return output;
  }

  Widget panelBuilder({
    required PPanel config,
    required DataContext parentDataContext,
    required DataBinding parentBinding,
    required ThemeData theme,
  }) {
    if (config.isStatic) {
      final widget = StaticPanel(
        content: panelExpansion(
          config: config,
          content: createChildren(
            parentBinding: parentBinding,
            theme: theme,
            dataContext: parentDataContext,
            children: config.children,
          ),
        ),
        parentDataContext: parentDataContext,
      );
      return widget;
    }

    throw UnimplementedError();
  }

  Widget createChild(
      {required DataContext dataContext,
      required PContent p,
      required DataBinding parentBinding,
      required ThemeData theme}) {
    /// Using switch stops from detecting PPart sub-classes
    if (p is PPanel) {
      final panel = panelBuilder(
        config: p,
        parentDataContext: dataContext,
        parentBinding: parentBinding,
        theme: theme,
      );
      return panel;
    } else if (p is PPart) {
      final part = partLibrary.partBuilder(
        partConfig: p,
        dataContext: dataContext,
        parentBinding: parentBinding,
        pageArguments: const {},
        theme: theme,
      );
      return part;
    }
    throw PreceptException('Unrecognised content');
  }

  Widget panelExpansion(
      {required PPanel config, required List<Widget> content}) {
    return config.panelStyle.expandable
        ? ExpansionTile(
            title: Text(config.caption ?? ''),
            children: content,
          )
        : Container(
            child: ListView(
              children: content,
            ),
          );
  }

  Route<dynamic>? constructRoute(
      String route, Map<String, dynamic> pageArguments, Widget pageWidget) {
    return MaterialPageRoute(
        settings: RouteSettings(
          name: route,
          arguments: pageArguments,
        ),
        builder: (_) => pageWidget);
  }

  /// When a route contains an object reference, that part of the route is ignored.
  /// When present is should be in the form of 'objectId==xxxxxx'
  Route<dynamic>? _autoGeneratedRoute(
    String route,
    List<String> routeSegments,
    BuildContext context,
    Map<String, dynamic> pageArguments,
    PScript script,
    DocumentCache cache,
  ) {
    final documentClassName = routeSegments[1];
    final routeOnly = '${routeSegments[0]}/${routeSegments[1]}';

    /// Cast should be safe, as auto routes only generated from PPage
    PPage? pageConfig = script.routes[route] as PPage?;
    if (pageConfig == null) {
      return null;
    }
    PData dataSelector = PSingle();

    /// this gets replaced
    if (routeSegments.length > 2) {
      final selectorTag = routeSegments[2];
      final found = pageConfig.dataSelectors
          .where((element) => element.tag == selectorTag);
      if (found.isEmpty) {
        String msg = 'Data selector tag \'$selectorTag\'not found';
        logType(this.runtimeType).e(msg);
        throw PreceptException(msg);
      }
      if (found.length > 1) {
        String msg = 'Duplicate data selector tag \'$selectorTag\' found';
        logType(this.runtimeType).e(msg);
        throw PreceptException(msg);
      }
      dataSelector = found.first;
    }

    PDocument? documentSchema = script.schema.documents[documentClassName];
    if (documentSchema == null) {
      String msg =
          "document schema '$documentSchema' has not been declared in the schema, but has been allocated a route";
      logType(this.runtimeType).e(msg);
      throw PreceptException(msg);
    }

    final DataContext dataContext =
        DefaultDataContext(classCache: cache.getClassCache(config: pageConfig));
    final pageBuilder = inject<PageBuilder>();
    final pageWidget = (dataSelector.isSingle)
        ? DocumentPage(
            dataContext: dataContext,
            pageBuilder: pageBuilder,
            pageArguments: pageArguments,
            config: pageConfig,
            objectId:
                (dataSelector is PSingleById) ? dataSelector.objectId : null,
            route: route,
          )
        : DocumentListPage(
            dataContext: cache.dataContext(
              dataSelector: dataSelector,
              parentDataContext: NullDataContext(),
              config: pageConfig,
            ),
            pageArguments: pageArguments,
            config: pageConfig,
            route: route,
            objectIds:
                (dataSelector is PMultiById) ? dataSelector.objectIds : null,
          );
    return constructRoute(
      routeOnly,
      pageArguments,
      pageWidget,
    );
  }
}
