name: takkan_back4app_client
description: Client-side Takkan pacage for use with Back4App
version: 0.0.1
homepage: https://www.takkan.org

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  parse_server_sdk: ^5.1.2
  dio: ^5.2.1+1
  json_annotation: ^4.4.0
  process_runner: ^4.1.2
  meta: ^1.7.0
  takkan_script: ^0.0.1
  takkan_schema: ^0.1.0
  takkan_backend: ^0.0.1



dev_dependencies:
  test:
  build_runner:
  mockito: ^5.0.7
  json_serializable: ^6.1.4
  takkan_medley_orchestrator: ^0.0.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

