name: takkan_medley_orchestrator
description: Script and Schema for takkan_medley
version: 0.0.1
homepage: https://www.takkan.org/

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  takkan_script:
    path: ../takkan_script
  takkan_schema:
    path: ../takkan_schema
dev_dependencies:
  test: ^1.16.0




